const productsData = [
    {
        "id": "apple-fut-1",
        "brand": "apple",
        "name": "iPhone 17 Pro",
        "rating": "5.0",
        "feature": "A19 Bionic & 2nm Chip",
        "price": 185000,
        "image": "images/iphone-17-pro.png",
        "badge": "Future",
        "category": "smartphones"
    },
    {
        "id": "apple-16-pm",
        "brand": "apple",
        "name": "iPhone 16 Pro Max",
        "rating": "4.9",
        "feature": "Ultra Titanium Shell",
        "price": 175000,
        "image": "images/iphone-15-pro-natural.png",
        "badge": "Latest",
        "category": "smartphones"
    },
    {
        "id": "samsung-s25-u",
        "brand": "samsung",
        "name": "Galaxy S25 Ultra",
        "rating": "4.9",
        "feature": "Snapdragon 8 Gen 4",
        "price": 145000,
        "image": "images/samsung-s25-ultra.png",
        "badge": "Upcoming",
        "category": "smartphones"
    },
    {
        "id": "google-p10-p",
        "brand": "google",
        "name": "Pixel 10 Pro",
        "rating": "4.8",
        "feature": "Tensor G5 AI Engine",
        "price": 115000,
        "image": "images/pixel-10-pro.png",
        "badge": "Future",
        "category": "smartphones"
    },
    {
        "id": "apple-0",
        "brand": "apple",
        "name": "iPhone 15 Pro Max",
        "rating": "4.7",
        "feature": "Titanium Design",
        "price": 160000,
        "image": "images/iphone-15-pro-natural.png",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "apple-1",
        "brand": "apple",
        "name": "iPhone 15 Pro",
        "rating": "4.9",
        "feature": "A17 Pro Chip",
        "price": 150000,
        "image": "images/apple-iphone-15-pro.jpg",
        "badge": "Hot",
        "category": "smartphones"
    },
    {
        "id": "apple-2",
        "brand": "apple",
        "name": "iPhone 15 Plus",
        "rating": "4.6",
        "feature": "Dynamic Island",
        "price": 140000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-plus.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "apple-3",
        "brand": "apple",
        "name": "iPhone 15",
        "rating": "4.5",
        "feature": "Super Retina XDR",
        "price": 130000,
        "image": "images/apple-iphone-15.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "samsung-0",
        "brand": "samsung",
        "name": "Galaxy S24 Ultra",
        "rating": "4.9",
        "feature": "Titanium Build",
        "price": 129999,
        "image": "https://images.samsung.com/is/image/samsung/p6pim/us/sm-s938uzbfxaa/gallery/us-galaxy-s25-s938-536276-sm-s938uzbfxaa-548617513",
        "badge": "Best Seller",
        "category": "smartphones"
    },
    {
        "id": "samsung-1",
        "brand": "samsung",
        "name": "Galaxy S24+",
        "rating": "4.8",
        "feature": "Snapdragon 8 Gen 3",
        "price": 99999,
        "image": "https://images.samsung.com/is/image/samsung/p6pim/us/2501/gallery/us-galaxy-s25-s936-536279-sm-s936uzdaxaa-544888374",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "apple-4",
        "brand": "apple",
        "name": "iPhone 14 Pro Max",
        "rating": "4.8",
        "feature": "ProMotion 120Hz",
        "price": 120000,
        "image": "images/apple-iphone-14-pro-max.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "apple-5",
        "brand": "apple",
        "name": "iPhone 14 Pro",
        "rating": "4.0",
        "feature": "Ceramic Shield",
        "price": 110000,
        "image": "images/apple-iphone-14-pro.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "apple-6",
        "brand": "apple",
        "name": "iPhone 14",
        "rating": "4.8",
        "feature": "MagSafe Compatible",
        "price": 100000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "apple-7",
        "brand": "apple",
        "name": "iPhone 13",
        "rating": "4.5",
        "feature": "A15 Bionic",
        "price": 90000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "apple-8",
        "brand": "apple",
        "name": "iPhone SE (2022)",
        "rating": "4.8",
        "feature": "Classic Design",
        "price": 80000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-se-2022.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "apple-9",
        "brand": "apple",
        "name": "iPhone 12",
        "rating": "4.5",
        "feature": "5G Capable",
        "price": 70000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-12.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "samsung-0",
        "brand": "samsung",
        "name": "Galaxy S24 Ultra",
        "rating": "4.6",
        "feature": "Galaxy AI",
        "price": 140000,
        "image": "https://images.samsung.com/is/image/samsung/p6pim/us/sm-s938uzbfxaa/gallery/us-galaxy-s25-s938-536276-sm-s938uzbfxaa-548617513",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "samsung-1",
        "brand": "samsung",
        "name": "Galaxy S24+",
        "rating": "4.7",
        "feature": "Snapdragon 8 Gen 3",
        "price": 128000,
        "image": "https://images.samsung.com/is/image/samsung/p6pim/us/2501/gallery/us-galaxy-s25-s936-536279-sm-s936uzdaxaa-544888374",
        "badge": "New",
        "category": "smartphones"
    },
    {
        "id": "samsung-2",
        "brand": "samsung",
        "name": "Galaxy S24",
        "rating": "4.3",
        "feature": "Dynamic AMOLED",
        "price": 116000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-5g.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "samsung-3",
        "brand": "samsung",
        "name": "Galaxy Z Fold 5",
        "rating": "4.1",
        "feature": "Foldable Display",
        "price": 104000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-fold5.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "samsung-4",
        "brand": "samsung",
        "name": "Galaxy Z Flip 5",
        "rating": "4.5",
        "feature": "Flex Window",
        "price": 92000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip5.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "samsung-5",
        "brand": "samsung",
        "name": "Galaxy S23 Ultra",
        "rating": "4.8",
        "feature": "200MP Camera",
        "price": 80000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s23-ultra-5g.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "samsung-6",
        "brand": "samsung",
        "name": "Galaxy S23 FE",
        "rating": "4.1",
        "feature": "Fan Edition",
        "price": 68000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s23-fe.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "samsung-7",
        "brand": "samsung",
        "name": "Galaxy A54 5G",
        "rating": "4.9",
        "feature": "Awesome Camera",
        "price": 56000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a54.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "samsung-8",
        "brand": "samsung",
        "name": "Galaxy A34",
        "rating": "4.4",
        "feature": "Vibrant Display",
        "price": 44000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a34.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "samsung-9",
        "brand": "samsung",
        "name": "Galaxy M14",
        "rating": "4.2",
        "feature": "Massive Battery",
        "price": 32000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m14-5g.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "google-0",
        "brand": "google",
        "name": "Pixel 8 Pro",
        "rating": "4.4",
        "feature": "Tensor G3",
        "price": 110000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8-pro.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "google-1",
        "brand": "google",
        "name": "Pixel 8",
        "rating": "4.8",
        "feature": "AI Photography",
        "price": 102000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8.jpg",
        "badge": "New",
        "category": "smartphones"
    },
    {
        "id": "google-2",
        "brand": "google",
        "name": "Pixel 7 Pro",
        "rating": "4.6",
        "feature": "Macro Focus",
        "price": 94000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-7-pro.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "google-3",
        "brand": "google",
        "name": "Pixel 7",
        "rating": "4.6",
        "feature": "Magic Eraser",
        "price": 86000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-7.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "google-4",
        "brand": "google",
        "name": "Pixel 7a",
        "rating": "4.1",
        "feature": "Affordable Flagship",
        "price": 78000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-7a.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "google-5",
        "brand": "google",
        "name": "Pixel Fold",
        "rating": "4.6",
        "feature": "Foldable UI",
        "price": 70000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-fold.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "google-6",
        "brand": "google",
        "name": "Pixel 6 Pro",
        "rating": "4.3",
        "feature": "Tensor G1",
        "price": 62000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-6-pro.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "google-7",
        "brand": "google",
        "name": "Pixel 6",
        "rating": "4.2",
        "feature": "Material You",
        "price": 54000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-6.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "google-8",
        "brand": "google",
        "name": "Pixel 6a",
        "rating": "4.3",
        "feature": "Compact Design",
        "price": 46000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-6a.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "google-9",
        "brand": "google",
        "name": "Pixel 5",
        "rating": "4.1",
        "feature": "Classic Pixel",
        "price": 38000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-5.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "oneplus-0",
        "brand": "oneplus",
        "name": "OnePlus 12",
        "rating": "4.8",
        "feature": "Hasselblad Camera",
        "price": 95000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-12.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "oneplus-1",
        "brand": "oneplus",
        "name": "OnePlus 12R",
        "rating": "4.2",
        "feature": "Performance Beast",
        "price": 88000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-12r.jpg",
        "badge": "New",
        "category": "smartphones"
    },
    {
        "id": "oneplus-2",
        "brand": "oneplus",
        "name": "OnePlus Open",
        "rating": "4.6",
        "feature": "Apex Foldable",
        "price": 81000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-open.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "oneplus-3",
        "brand": "oneplus",
        "name": "OnePlus 11",
        "rating": "4.6",
        "feature": "Snapdragon 8 Gen 2",
        "price": 74000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-11.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "oneplus-4",
        "brand": "oneplus",
        "name": "OnePlus 11R",
        "rating": "4.1",
        "feature": "Alert Slider",
        "price": 67000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-11r.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "oneplus-5",
        "brand": "oneplus",
        "name": "OnePlus Nord 3",
        "rating": "4.7",
        "feature": "Nord Premium",
        "price": 60000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-3.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "oneplus-6",
        "brand": "oneplus",
        "name": "OnePlus Nord CE 3",
        "rating": "4.1",
        "feature": "Core Edition",
        "price": 53000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-ce3.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "oneplus-7",
        "brand": "oneplus",
        "name": "OnePlus 10 Pro",
        "rating": "4.9",
        "feature": "Flagship Killer",
        "price": 46000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-10-pro.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "oneplus-8",
        "brand": "oneplus",
        "name": "OnePlus 10T",
        "rating": "4.0",
        "feature": "150W Charging",
        "price": 39000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-10t.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "oneplus-9",
        "brand": "oneplus",
        "name": "OnePlus 9 Pro",
        "rating": "4.4",
        "feature": "Fluid AMOLED",
        "price": 32000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-9-pro.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "xiaomi-0",
        "brand": "xiaomi",
        "name": "Xiaomi 14 Ultra",
        "rating": "4.6",
        "feature": "Leica Optics",
        "price": 105000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14-ultra.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "xiaomi-1",
        "brand": "xiaomi",
        "name": "Xiaomi 14 Pro",
        "rating": "4.5",
        "feature": "HyperOS",
        "price": 96000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14-pro.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "xiaomi-2",
        "brand": "xiaomi",
        "name": "Xiaomi 14",
        "rating": "4.1",
        "feature": "Compact Flagship",
        "price": 87000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-14.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "xiaomi-3",
        "brand": "xiaomi",
        "name": "Redmi Note 13 Pro+",
        "rating": "4.5",
        "feature": "200MP Curved Display",
        "price": 78000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-13-pro-plus.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "xiaomi-4",
        "brand": "xiaomi",
        "name": "Redmi Note 13 Pro",
        "rating": "4.5",
        "feature": "Value King",
        "price": 69000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-13-pro.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "xiaomi-5",
        "brand": "xiaomi",
        "name": "POCO X6 Pro",
        "rating": "4.2",
        "feature": "Gaming Performance",
        "price": 60000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-x6-pro.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "xiaomi-6",
        "brand": "xiaomi",
        "name": "POCO F5",
        "rating": "4.6",
        "feature": "Snapdragon 7+ Gen 2",
        "price": 51000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-f5.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "xiaomi-7",
        "brand": "xiaomi",
        "name": "Xiaomi 13 Pro",
        "rating": "4.5",
        "feature": "Premium Build",
        "price": 42000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-13-pro.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "xiaomi-8",
        "brand": "xiaomi",
        "name": "Redmi 12 5G",
        "rating": "4.3",
        "feature": "Budget 5G",
        "price": 33000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-12-5g.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "xiaomi-9",
        "brand": "xiaomi",
        "name": "Xiaomi Pad 6",
        "rating": "4.1",
        "feature": "Productivity Beast",
        "price": 24000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-pad-6.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "asus-0",
        "brand": "asus",
        "name": "ROG Phone 8 Pro",
        "rating": "4.2",
        "feature": "Gaming Beast",
        "price": 100000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-8-pro.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "asus-1",
        "brand": "asus",
        "name": "ROG Phone 8",
        "rating": "4.2",
        "feature": "AeroActive Cooler",
        "price": 94000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-8.jpg",
        "badge": "New",
        "category": "smartphones"
    },
    {
        "id": "asus-2",
        "brand": "asus",
        "name": "ROG Phone 7 Ultimate",
        "rating": "4.4",
        "feature": "Matrix Display",
        "price": 88000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-7-ultimate.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "asus-3",
        "brand": "asus",
        "name": "ROG Phone 7",
        "rating": "4.4",
        "feature": "Snapdragon 8 Gen 2",
        "price": 82000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-7.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "asus-4",
        "brand": "asus",
        "name": "Zenfone 10",
        "rating": "4.1",
        "feature": "Compact Flagship",
        "price": 76000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/asus-zenfone-10.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "asus-5",
        "brand": "asus",
        "name": "Zenfone 9",
        "rating": "4.2",
        "feature": "Gimbal Camera",
        "price": 70000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/asus-zenfone-9.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "asus-6",
        "brand": "asus",
        "name": "ROG Phone 6",
        "rating": "4.3",
        "feature": "165Hz Display",
        "price": 64000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-6.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "asus-7",
        "brand": "asus",
        "name": "ROG Phone 5s",
        "rating": "4.3",
        "feature": "AirTriggers",
        "price": 58000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-5s.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "asus-8",
        "brand": "asus",
        "name": "Zenfone 8",
        "rating": "4.9",
        "feature": "Pocket Size",
        "price": 52000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/asus-zenfone-8.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "asus-9",
        "brand": "asus",
        "name": "ROG Phone 3",
        "rating": "4.6",
        "feature": "Classic ROG",
        "price": 46000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/asus-rog-phone-3.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "nothing-0",
        "brand": "nothing",
        "name": "Nothing Phone (2)",
        "rating": "4.7",
        "feature": "Glyph Interface",
        "price": 62000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2.jpg",
        "badge": "Hot",
        "category": "smartphones"
    },
    {
        "id": "nothing-1",
        "brand": "nothing",
        "name": "Nothing Phone (2a)",
        "rating": "4.7",
        "feature": "Unique Design",
        "price": 58000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2a.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "nothing-2",
        "brand": "nothing",
        "name": "Nothing Phone (1)",
        "rating": "4.5",
        "feature": "Transparent Back",
        "price": 54000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-1.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "nothing-3",
        "brand": "nothing",
        "name": "CMF Phone 1",
        "rating": "4.2",
        "feature": "Modular Design",
        "price": 50000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/nothing-cmf-phone-1.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "nothing-4",
        "brand": "nothing",
        "name": "Phone (2) White",
        "rating": "4.2",
        "feature": "Nothing OS 2.5",
        "price": 46000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "nothing-5",
        "brand": "nothing",
        "name": "Phone (2) Dark",
        "rating": "4.3",
        "feature": "Minimalist UI",
        "price": 42000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "nothing-6",
        "brand": "nothing",
        "name": "Phone (1) White",
        "rating": "4.1",
        "feature": "Premium Feel",
        "price": 38000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-1.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "nothing-7",
        "brand": "nothing",
        "name": "Phone (2a) Milk",
        "rating": "4.7",
        "feature": "Matte Finish",
        "price": 34000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-1.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "nothing-8",
        "brand": "nothing",
        "name": "Phone (2a) Black",
        "rating": "4.2",
        "feature": "Iconic Look",
        "price": 30000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2a.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "nothing-9",
        "brand": "nothing",
        "name": "Nothing Concept",
        "rating": "4.6",
        "feature": "Future Vision",
        "price": 26000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/nothing-phone-2.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "sony-0",
        "brand": "sony",
        "name": "Xperia 1 V",
        "rating": "4.7",
        "feature": "Cinematic Display",
        "price": 115000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-1-v.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "sony-1",
        "brand": "sony",
        "name": "Xperia 5 V",
        "rating": "4.3",
        "feature": "Compact Creator",
        "price": 107000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-5-v.jpg",
        "badge": "New",
        "category": "smartphones"
    },
    {
        "id": "sony-2",
        "brand": "sony",
        "name": "Xperia 10 V",
        "rating": "4.3",
        "feature": "Battery Monster",
        "price": 99000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-10-v.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "sony-3",
        "brand": "sony",
        "name": "Xperia 1 IV",
        "rating": "4.8",
        "feature": "True Optical Zoom",
        "price": 91000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-1-iv.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "sony-4",
        "brand": "sony",
        "name": "Xperia 5 IV",
        "rating": "4.2",
        "feature": "Alpha Tech",
        "price": 83000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-5-iv.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "sony-5",
        "brand": "sony",
        "name": "Xperia Pro-I",
        "rating": "4.0",
        "feature": "1.0-type Sensor",
        "price": 75000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-10-iv.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "sony-6",
        "brand": "sony",
        "name": "Xperia 1 III",
        "rating": "4.5",
        "feature": "4K OLED",
        "price": 67000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-1-iii.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "sony-7",
        "brand": "sony",
        "name": "Xperia 5 III",
        "rating": "4.2",
        "feature": "Creator Mode",
        "price": 59000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-5-iii.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "sony-8",
        "brand": "sony",
        "name": "Xperia 10 III",
        "rating": "4.6",
        "feature": "Water Resistant",
        "price": 51000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-pro-i.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "sony-9",
        "brand": "sony",
        "name": "Xperia 1 II",
        "rating": "4.1",
        "feature": "Classic Xperia",
        "price": 43000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/sony-xperia-10-iii.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "apple-ipad-0",
        "brand": "apple",
        "name": "iPad Pro 13-inch (M4)",
        "rating": "4.9",
        "feature": "M4 Chip, Tandem OLED",
        "price": 129900,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-13-2024.jpg",
        "badge": "New",
        "category": "smartphones"
    },
    {
        "id": "apple-ipad-1",
        "brand": "apple",
        "name": "iPad Air 13-inch (M2)",
        "rating": "4.7",
        "feature": "M2 Chip, Liquid Retina",
        "price": 79900,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-air-13-m2.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "apple-ipad-2",
        "brand": "apple",
        "name": "iPad (10th gen)",
        "rating": "4.5",
        "feature": "A14 Bionic, 10.9-inch",
        "price": 39900,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-2022.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "apple-ipad-3",
        "brand": "apple",
        "name": "iPad mini (6th gen)",
        "rating": "4.6",
        "feature": "A15 Bionic, 8.3-inch",
        "price": 49900,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-mini-2021.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "samsung-tab-0",
        "brand": "samsung",
        "name": "Galaxy Tab S9 Ultra",
        "rating": "4.8",
        "feature": "Snapdragon 8 Gen 2, 14.6\"",
        "price": 119999,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s9-ultra.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "samsung-tab-1",
        "brand": "samsung",
        "name": "Galaxy Tab S9+",
        "rating": "4.7",
        "feature": "Snapdragon 8 Gen 2, 12.4\"",
        "price": 90999,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s9-plus.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "samsung-tab-2",
        "brand": "samsung",
        "name": "Galaxy Tab S9 FE",
        "rating": "4.4",
        "feature": "Exynos 1380, 10.9\"",
        "price": 44999,
        "image": "https://images.samsung.com/is/image/samsung/p6pim/us/sm-x520nzsexar/gallery/us-galaxy-tab-s10-fe-sm-x526-sm-x520nzsexar-550966782",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "xiaomi-pad-0",
        "brand": "xiaomi",
        "name": "Xiaomi Pad 6",
        "rating": "4.5",
        "feature": "Snapdragon 870, 11\"",
        "price": 26999,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-pad-6.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "oneplus-pad-0",
        "brand": "oneplus",
        "name": "OnePlus Pad",
        "rating": "4.6",
        "feature": "Dimensity 9000, 11.61\"",
        "price": 37999,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-pad.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "apple-acc-0",
        "brand": "apple",
        "name": "AirPods Pro (2nd gen)",
        "rating": "4.9",
        "feature": "Active Noise Cancellation",
        "price": 24900,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-airpods-pro-2nd-generation.jpg",
        "badge": "Hot",
        "category": "smartphones"
    },
    {
        "id": "apple-acc-1",
        "brand": "apple",
        "name": "AirPods Max",
        "rating": "4.6",
        "feature": "High-fidelity audio",
        "price": 59900,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-airpods-max.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "apple-acc-2",
        "brand": "apple",
        "name": "Apple Watch Ultra 2",
        "rating": "4.8",
        "feature": "Rugged Titanium",
        "price": 89900,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-ultra2.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "apple-acc-3",
        "brand": "apple",
        "name": "Apple Watch Series 9",
        "rating": "4.7",
        "feature": "Double Tap gesture",
        "price": 41900,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-series-9.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "samsung-acc-0",
        "brand": "samsung",
        "name": "Galaxy Buds2 Pro",
        "rating": "4.6",
        "feature": "24-bit Hi-Fi audio",
        "price": 17999,
        "image": "https://images.samsung.com/is/image/samsung/p6pim/us/sm-r630nzaaxar/gallery/us--sm-r630nzaaxar-550360616",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "samsung-acc-1",
        "brand": "samsung",
        "name": "Galaxy Watch6 Classic",
        "rating": "4.7",
        "feature": "Rotating bezel",
        "price": 36999,
        "image": "https://images.samsung.com/is/image/samsung/p6pim/us/f2507/gallery/us-galaxy-watch8-l330-sm-l330nzsaxaa-547908172",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "google-acc-0",
        "brand": "google",
        "name": "Pixel Buds Pro",
        "rating": "4.5",
        "feature": "Silent Seal ANC",
        "price": 19990,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-buds-pro.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "google-acc-1",
        "brand": "google",
        "name": "Pixel Watch 2",
        "rating": "4.4",
        "feature": "Advanced health sensors",
        "price": 39900,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-watch-2.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "oneplus-acc-0",
        "brand": "oneplus",
        "name": "OnePlus Buds Pro 2",
        "rating": "4.6",
        "feature": "MelodyBoost Dual Drivers",
        "price": 11999,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/oneplus-buds-pro-2.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "apple-case-0",
        "brand": "apple",
        "name": "iPhone 15 Pro FineWoven Case",
        "rating": "4.1",
        "feature": "MagSafe Compatible",
        "price": 5900,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-pro.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "samsung-case-0",
        "brand": "samsung",
        "name": "Galaxy S24 Ultra Silicone Case",
        "rating": "4.5",
        "feature": "Soft-touch grip",
        "price": 3499,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-ultra-5g.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "apple-charger-0",
        "brand": "apple",
        "name": "Apple 20W USB-C Power Adapter",
        "rating": "4.8",
        "feature": "Fast Charging",
        "price": 1900,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "samsung-charger-0",
        "brand": "samsung",
        "name": "Samsung 45W Power Adapter",
        "rating": "4.7",
        "feature": "Super Fast Charging 2.0",
        "price": 2999,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-5g.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "anker-charger-0",
        "brand": "anker",
        "name": "Anker Nano II 65W",
        "rating": "4.9",
        "feature": "GaN II Technology",
        "price": 3999,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8.jpg",
        "badge": "Hot",
        "category": "smartphones"
    },
    {
        "id": "sony-headphone-0",
        "brand": "sony",
        "name": "Sony WH-1000XM5",
        "rating": "4.8",
        "feature": "Industry Leading ANC",
        "price": 29990,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/sony-wf-1000xm5.jpg",
        "badge": "Top Rated",
        "category": "smartphones"
    },
    {
        "id": "bose-headphone-0",
        "brand": "bose",
        "name": "Bose QuietComfort Ultra",
        "rating": "4.7",
        "feature": "Immersive Audio",
        "price": 35900,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-airpods-max.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "apple-magsafe-0",
        "brand": "apple",
        "name": "Apple MagSafe Charger",
        "rating": "4.6",
        "feature": "15W Wireless Charging",
        "price": 4500,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-pro-max.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "anker-powerbank-0",
        "brand": "anker",
        "name": "Anker PowerCore Magnetic 5K",
        "rating": "4.5",
        "feature": "MagSafe Compatible Power Bank",
        "price": 4999,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-8-pro.jpg",
        "badge": null,
        "category": "smartphones"
    },
    {
        "id": "watch-0",
        "brand": "apple",
        "name": "Apple Watch Ultra 2",
        "rating": "4.9",
        "feature": "Titanium Case",
        "price": 89000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-watch-ultra2.jpg",
        "badge": "Premium",
        "category": "accessories",
        "type": "watch"
    },
    {
        "id": "watch-1",
        "brand": "samsung",
        "name": "Galaxy Watch 6 Classic",
        "rating": "4.8",
        "feature": "Rotating Bezel",
        "price": 45000,
        "image": "https://images.samsung.com/is/image/samsung/p6pim/us/f2507/gallery/us-galaxy-watch8-l330-sm-l330nzsaxaa-547908172",
        "badge": "Hot",
        "category": "accessories",
        "type": "watch"
    },
    {
        "id": "watch-2",
        "brand": "google",
        "name": "Pixel Watch 2",
        "rating": "4.6",
        "feature": "Fitbit Integration",
        "price": 35000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/google-pixel-watch-2.jpg",
        "badge": null,
        "category": "accessories",
        "type": "watch"
    },
    {
        "id": "audio-0",
        "brand": "apple",
        "name": "AirPods Pro Gen 2",
        "rating": "4.9",
        "feature": "Active Noise Cancellation",
        "price": 25000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-airpods-pro-2nd-generation.jpg",
        "badge": "Best Seller",
        "category": "accessories",
        "type": "audio"
    },
    {
        "id": "audio-1",
        "brand": "sony",
        "name": "Sony WF-1000XM5",
        "rating": "4.8",
        "feature": "Hi-Res Audio",
        "price": 29000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/sony-wf-1000xm5.jpg",
        "badge": null,
        "category": "accessories",
        "type": "audio"
    },
    {
        "id": "speaker-0",
        "brand": "apple",
        "name": "HomePod Mini",
        "rating": "4.7",
        "feature": "360 Audio",
        "price": 10000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-homepod-mini.jpg",
        "badge": null,
        "category": "accessories",
        "type": "audio"
    },
    {
        "id": "speaker-1",
        "brand": "apple",
        "name": "Apple HomePod (2nd Gen)",
        "rating": "4.9",
        "feature": "High-fidelity, room-filling sound",
        "price": 29900,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-homepod-2023.jpg",
        "badge": "Premium",
        "category": "accessories",
        "type": "audio"
    },
    {
        "id": "tablet-0",
        "brand": "apple",
        "name": "iPad Pro M4",
        "rating": "5.0",
        "feature": "OLED Display",
        "price": 110000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-2024.jpg",
        "badge": "Future",
        "category": "tablets",
        "type": "tablet"
    },
    {
        "id": "tablet-1",
        "brand": "samsung",
        "name": "Galaxy Tab S9 Ultra",
        "rating": "4.9",
        "feature": "S-Pen Included",
        "price": 120000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s9-ultra.jpg",
        "badge": null,
        "category": "tablets",
        "type": "tablet"
    },
    {
        "id": "tablet-2",
        "brand": "xiaomi",
        "name": "Xiaomi Pad 6 Max",
        "rating": "4.6",
        "feature": "14-inch Display",
        "price": 50000,
        "image": "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-pad-6.jpg",
        "badge": null,
        "category": "tablets",
        "type": "tablet"
    }
];
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { productsData };
} else {
    window.productsData = productsData;
}

