// download_official_images.js
// Reads official_images.json (generated by get_og_images.js) and downloads each image into images/official/<id>.jpg

const fs = require('fs');
const path = require('path');
const https = require('https');

const mappingPath = path.join(__dirname, 'official_images.json');
if (!fs.existsSync(mappingPath)) {
  console.error('Mapping file not found:', mappingPath);
  process.exit(1);
}
const mapping = JSON.parse(fs.readFileSync(mappingPath, 'utf-8'));

const outputDir = path.join(__dirname, '..', 'images', 'official');
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

function downloadImage(url, dest) {
  return new Promise((resolve, reject) => {
    const file = fs.createWriteStream(dest);
    https.get(url, (response) => {
      if (response.statusCode !== 200) {
        reject(new Error('Failed to get ' + url + ' status code: ' + response.statusCode));
        return;
      }
      response.pipe(file);
      file.on('finish', () => {
        file.close(() => resolve());
      });
    }).on('error', (err) => {
      fs.unlink(dest, () => {});
      reject(err);
    });
  });
}

(async () => {
  for (const [id, url] of Object.entries(mapping)) {
    const ext = path.extname(new URL(url).pathname) || '.jpg';
    const destPath = path.join(outputDir, `${id}${ext}`);
    try {
      await downloadImage(url, destPath);
      console.log(`Downloaded ${id} -> ${destPath}`);
    } catch (err) {
      console.error(`Failed to download ${id} from ${url}:`, err.message);
    }
  }
  console.log('All downloads attempted.');
})();
